### ISSUE TITLE
SPページ作成

### ISSUE THREAD

**Issue by Arainana** [aprilknights-inc/portman#3]
- [x] CSS

https://xd.adobe.com/spec/181c3a1c-cbb3-4f7f-417e-1c1192dfdb01-6e2d/screen/71245a4d-0a84-433a-a4b1-6a914251fffd/iPhone-X-XS-1/

横幅768pxまではPC、それ以下のサイズからスマホ用のスタイルが適用されるようにして下さい！

**Comment by saitaniya** [comment]
2019/07/05 完了したためクローズ
